const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.googleplay,
		C3.Plugins.advert,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.Pin,
		C3.Behaviors.solid,
		C3.Plugins.NinePatch,
		C3.Plugins.Text,
		C3.Behaviors.Tween,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.JavaScriptInEvents.Gameplay_Event8_Act11,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Gameplay_Event11_Act5,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnError,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.advert.Acts.CreateInterstitial,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.advert.Cnds.IsInterstitialLoaded,
		C3.Plugins.advert.Acts.ShowInterstitial,
		C3.Plugins.advert.Cnds.IsRewardedLoaded,
		C3.Plugins.advert.Acts.ShowRewarded,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetEffectParam
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Touch: 0},
	{GooglePlay: 0},
	{MobileAdvert: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{arShopItens: 0},
	{Database: 0},
	{Browser: 0},
	{onCollider: 0},
	{fruitBanana: 0},
	{fruitOrante: 0},
	{fruitPeach: 0},
	{fruitStrawberry: 0},
	{game1Bg: 0},
	{life: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{playerGame1: 0},
	{Pin: 0},
	{girlAnim: 0},
	{playerShadow: 0},
	{Solid: 0},
	{ground: 0},
	{id: 0},
	{lifeGame1: 0},
	{background: 0},
	{bird: 0},
	{scored: 0},
	{bottomPipe: 0},
	{tiledBgGame3Down: 0},
	{tiledBgGame3Top: 0},
	{topPipe: 0},
	{tiledBGGame2: 0},
	{blockGame2: 0},
	{playerGame2: 0},
	{trapGame2: 0},
	{TiledBackground: 0},
	{gameIcon: 0},
	{btnGameBack: 0},
	{gameIcon2: 0},
	{gameIcon3: 0},
	{collected: 0},
	{coin: 0},
	{btnPlay: 0},
	{btnOptions: 0},
	{btnShop: 0},
	{logoGame: 0},
	{ticjoyLogo: 0},
	{"9patchBtn": 0},
	{"9patchBg": 0},
	{shopBtn: 0},
	{txtMenus: 0},
	{txtMenuTittle: 0},
	{txtGameplay: 0},
	{txtShop: 0},
	{pauseOverBg: 0},
	{pauseSelect: 0},
	{btnPause: 0},
	{txtPause: 0},
	{pauseBgBtn: 0},
	{btnGameOver: 0},
	{bg1: 0},
	{optBtn0: 0},
	{Tween: 0},
	{optSliders: 0},
	{optBtn1: 0},
	{optBtn2: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{"9patch": 0},
	{btnPlayVideo: 0},
	{Sprite3: 0},
	{Bullet: 0},
	{famFruits: 0},
	{btnEffects: 0},
	{sliderSpeed: 0},
	{minX: 0},
	{maxX: 0},
	{posY: 0},
	{newPosition: 0},
	{schrollSpeed: 0},
	{nextValue: 0},
	{indexBlock: 0},
	{jumpStrength: 0},
	{startX: 0},
	{maxY: 0},
	{minY: 0},
	{distPipes: 0},
	{secondsPerObstacle: 0},
	{randomizeCoin: 0},
	{posX: 0},
	{uidButton: 0},
	{startGame: 0},
	{gameOver: 0},
	{coins: 0},
	{scoreGame: 0},
	{recordGame1: 0},
	{recordGame2: 0},
	{recordGame3: 0},
	{onPause: 0},
	{soundMusic: 0},
	{soundEffects: 0},
	{languageId: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	GooglePlay: class extends self.IInstance {},
	MobileAdvert: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	arShopItens: class extends self.IArrayInstance {},
	Database: class extends self.IDictionaryInstance {},
	Browser: class extends self.IInstance {},
	fruitBanana: class extends self.ISpriteInstance {},
	fruitOrante: class extends self.ISpriteInstance {},
	fruitPeach: class extends self.ISpriteInstance {},
	fruitStrawberry: class extends self.ISpriteInstance {},
	game1Bg: class extends self.ITiledBackgroundInstance {},
	playerGame1: class extends self.ISpriteInstance {},
	girlAnim: class extends self.ISpriteInstance {},
	playerShadow: class extends self.ISpriteInstance {},
	ground: class extends self.ITiledBackgroundInstance {},
	lifeGame1: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	bird: class extends self.ISpriteInstance {},
	bottomPipe: class extends self.ISpriteInstance {},
	tiledBgGame3Down: class extends self.ITiledBackgroundInstance {},
	tiledBgGame3Top: class extends self.ITiledBackgroundInstance {},
	topPipe: class extends self.ISpriteInstance {},
	tiledBGGame2: class extends self.ITiledBackgroundInstance {},
	blockGame2: class extends self.ITiledBackgroundInstance {},
	playerGame2: class extends self.ISpriteInstance {},
	trapGame2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	gameIcon: class extends self.ISpriteInstance {},
	btnGameBack: class extends self.ISpriteInstance {},
	gameIcon2: class extends self.ISpriteInstance {},
	gameIcon3: class extends self.ISpriteInstance {},
	coin: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnOptions: class extends self.ISpriteInstance {},
	btnShop: class extends self.ISpriteInstance {},
	logoGame: class extends self.ISpriteInstance {},
	ticjoyLogo: class extends self.ISpriteInstance {},
	_9patchBtn: class extends self.I9PatchInstance {},
	_9patchBg: class extends self.I9PatchInstance {},
	shopBtn: class extends self.ISpriteInstance {},
	txtMenus: class extends self.ITextInstance {},
	txtMenuTittle: class extends self.ITextInstance {},
	txtGameplay: class extends self.ITextInstance {},
	txtShop: class extends self.ITextInstance {},
	pauseOverBg: class extends self.ITiledBackgroundInstance {},
	pauseSelect: class extends self.ISpriteInstance {},
	btnPause: class extends self.ISpriteInstance {},
	txtPause: class extends self.ITextInstance {},
	pauseBgBtn: class extends self.ISpriteInstance {},
	btnGameOver: class extends self.ISpriteInstance {},
	bg1: class extends self.ITiledBackgroundInstance {},
	optBtn0: class extends self.ISpriteInstance {},
	optSliders: class extends self.ISpriteInstance {},
	optBtn1: class extends self.ISpriteInstance {},
	optBtn2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	_9patch: class extends self.I9PatchInstance {},
	btnPlayVideo: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	famFruits: class extends self.ISpriteInstance {},
	btnEffects: class extends self.ISpriteInstance {}
}